package input;

import org.lwjgl.glfw.GLFW;

public enum Buttons
{
	BUTTON_LEFT(GLFW.GLFW_MOUSE_BUTTON_LEFT),
	BUTTON_RIGHT(GLFW.GLFW_MOUSE_BUTTON_RIGHT),
	BUTTON_CENTER(GLFW.GLFW_MOUSE_BUTTON_MIDDLE),
	BUTTON_1(GLFW.GLFW_MOUSE_BUTTON_1),
	BUTTON_2(GLFW.GLFW_MOUSE_BUTTON_2),
	BUTTON_3(GLFW.GLFW_MOUSE_BUTTON_3),
	BUTTON_4(GLFW.GLFW_MOUSE_BUTTON_4),
	BUTTON_5(GLFW.GLFW_MOUSE_BUTTON_5),
	BUTTON_6(GLFW.GLFW_MOUSE_BUTTON_6),
	BUTTON_7(GLFW.GLFW_MOUSE_BUTTON_7),
	BUTTON_8(GLFW.GLFW_MOUSE_BUTTON_8);
	
	private int id;
	
	Buttons(int id) { this.id = id; }

	public int getId() { return id; }
}
