package graphics;

public enum TextureFilter
{
	TEXTURE_FILTER_NEAREST,
	TEXTURE_FILTER_LINEAR,
	TEXTURE_FILTER_NEAREST_MIPMAP_NEAREST,
	TEXTURE_FILTER_NEAREST_MIPMAP_LINEAR,
	TEXTURE_FILTER_LINEAR_MIPMAP_NEAREST,
	TEXTURE_FILTER_LINEAR_MIPMAP_LINEAR,
}
