package graphics;

public enum TextureFormat
{
	TEXTURE_FORMAT_R,
	TEXTURE_FORMAT_RG,
	TEXTURE_FORMAT_RGB,
	TEXTURE_FORMAT_RGBA,
	TEXTURE_FORMAT_FLOAT_R,
	TEXTURE_FORMAT_FLOAT_RG,
	TEXTURE_FORMAT_FLOAT_RGB,
	TEXTURE_FORMAT_FLOAT_RGBA,
	TEXTURE_FORMAT_DEPTH,
	TEXTURE_FORMAT_DEPTH16,
	TEXTURE_FORMAT_DEPTH24,
	TEXTURE_FORMAT_DEPTH32,
	TEXTURE_FORMAT_FLOAT_DEPTH32,
	TEXTURE_FORMAT_DEPTH_STENCIL
}
